CREATE OR REPLACE DATABASE FLIGHT;

CREATE OR REPLACE SCHEMA FLIGHT.RAW;

CREATE OR REPLACE WAREHOUSE FLIGHT_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;


CREATE OR REPLACE FILE FORMAT FLIGHT.RAW.FF_METADATA
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('\\N')
  SKIP_HEADER = 0;

CREATE OR REPLACE FILE FORMAT FLIGHT.RAW.FF_WEATHER_BTS
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL');


CREATE OR REPLACE STORAGE INTEGRATION S3_FLIGHT_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'Replace the ARN you obtained from AWS'
  STORAGE_ALLOWED_LOCATIONS = ('s3://flight-project-bucket-smit/');

DESC INTEGRATION S3_FLIGHT_INT;


CREATE OR REPLACE STAGE RAW.BTS_STAGE
  URL = 's3://flight-project-bucket-smit/bts/'
  STORAGE_INTEGRATION = S3_FLIGHT_INT
  FILE_FORMAT = (FORMAT_NAME = RAW.FF_WEATHER_BTS);

  
LIST @RAW.BTS_STAGE;
SHOW STAGES LIKE 'BTS_STAGE';

CREATE OR REPLACE STAGE RAW.AIRLINES_STAGE
  URL='s3://flight-project-bucket-smit/metadata/airlines.dat'
  STORAGE_INTEGRATION = S3_FLIGHT_INT
  FILE_FORMAT = RAW.FF_METADATA;

SHOW STAGES LIKE 'AIRLINES_STAGE';
LIST @RAW.AIRLINES_STAGE;

CREATE OR REPLACE STAGE RAW.AIRPORTS_STAGE
  URL='s3://flight-project-bucket-smit/metadata/airports.dat'
  STORAGE_INTEGRATION = S3_FLIGHT_INT
  FILE_FORMAT = RAW.FF_METADATA;


SHOW STAGES LIKE 'AIRPORTS_STAGE';
LIST @RAW.AIRPORTS_STAGE;



CREATE OR REPLACE STAGE RAW.WEATHER_STAGE
  URL='s3://flight-project-bucket-smit/weather/'
  STORAGE_INTEGRATION = S3_FLIGHT_INT
  FILE_FORMAT = RAW.FF_WEATHER_BTS;


  
SHOW STAGES LIKE 'WEATHER_STAGE';
LIST @RAW.WEATHER_STAGE;

