FLIGHT.STAGING_CORE.DIM_AIRLINESCREATE OR REPLACE TABLE RAW.AIRLINES_RAW (
  AIRLINE_ID STRING,
  NAME STRING,
  ALIAS STRING,
  IATA STRING,
  ICAO STRING,
  CALLSIGN STRING,
  COUNTRY STRING,
  ACTIVE STRING
);

CREATE OR REPLACE TABLE RAW.AIRPORTS_RAW (
  AIRPORT_ID STRING,
  NAME STRING,
  CITY STRING,
  COUNTRY STRING,
  IATA STRING,
  ICAO STRING,
  LATITUDE FLOAT,
  LONGITUDE FLOAT,
  ALTITUDE FLOAT,
  UTC_OFFSET STRING,
  DST STRING,
  TZ_NAME STRING,
  TYPE STRING,
  SOURCE STRING
);

CREATE OR REPLACE TABLE RAW.WEATHER_RAW (
    STATION STRING,
    DATE TIMESTAMP_NTZ,
    SOURCE STRING,
    LATITUDE FLOAT, 
    LONGITUDE FLOAT,
    ELEVATION FLOAT,
    NAME STRING,
    REPORT_TYPE STRING,
    CALL_SIGN STRING,
    QUALITY_CONTROL STRING,
    WND STRING,
    CIG STRING,
    VIS STRING,
    TMP STRING,
    DEW STRING,
    SLP STRING,
    AA1 STRING,
    AA2 STRING,
    AA3 STRING,
    AB1 STRING,
    AD1 STRING,
    AE1 STRING,
    AH1 STRING,
    AH2 STRING,
    AH3 STRING,
    AH4 STRING,
    AH5 STRING,
    AH6 STRING,
    AI1 STRING,
    AI2 STRING,
    AI3 STRING,
    AI4 STRING,
    AI5 STRING,
    AI6 STRING,
    AJ1 STRING,
    AK1 STRING,
    AL1 STRING,
    AM1 STRING,
    AN1 STRING,
    AT1 STRING,
    AT2 STRING,
    AT3 STRING,
    AT4 STRING,
    AU1 STRING,
    AU2 STRING,
    AU3 STRING,
    AW1 STRING,
    AW2 STRING,
    AW3 STRING,
    AW4 STRING,
    AX1 STRING,
    AX2 STRING,
    AX3 STRING,
    ED1 STRING,
    GA1 STRING,
    GA2 STRING,
    GA3 STRING,
    GD1 STRING,
    GD2 STRING,
    GD3 STRING,
    GD4 STRING,
    GE1 STRING,
    GF1 STRING,
    KA1 STRING,
    KA2 STRING,
    KB1 STRING,
    KB2 STRING,
    KB3 STRING,
    KC1 STRING,
    KC2 STRING,
    KD1 STRING,
    KD2 STRING,
    KE1 STRING,
    KG1 STRING,
    KG2 STRING,
    MA1 STRING,
    MD1 STRING,
    MF1 STRING,
    MG1 STRING,
    MH1 STRING,
    MK1 STRING,
    MV1 STRING,
    MW1 STRING,
    MW2 STRING,
    MW3 STRING,
    OC1 STRING,
    OD1 STRING,
    OE1 STRING,
    OE2 STRING,
    OE3 STRING,
    RH1 STRING,
    RH2 STRING,
    RH3 STRING,
    REM STRING,
    EQD STRING
);


CREATE OR REPLACE TABLE RAW.BTS_RAW (
    YEAR NUMBER,
    QUARTER NUMBER,
    MONTH NUMBER,
    DAY_OF_MONTH NUMBER,
    DAY_OF_WEEK NUMBER,
    FLIGHT_DATE DATE,
    MARKETING_AIRLINE_NETWORK STRING,
    OPERATED_OR_BRANDED_CODE_SHARE_PARTNERS STRING,
    DOT_ID_MARKETING_AIRLINE NUMBER,
    IATA_CODE_MARKETING_AIRLINE STRING,
    FLIGHT_NUMBER_MARKETING_AIRLINE STRING,
    ORIGINALLY_SCHEDULED_CODE_SHARE_AIRLINE STRING,
    DOT_ID_ORIGINALLY_SCHEDULED_CODE_SHARE_AIRLINE NUMBER,
    IATA_CODE_ORIGINALLY_SCHEDULED_CODE_SHARE_AIRLINE STRING,
    FLIGHT_NUM_ORIGINALLY_SCHEDULED_CODE_SHARE_AIRLINE STRING,
    OPERATING_AIRLINE STRING,
    DOT_ID_OPERATING_AIRLINE NUMBER,
    IATA_CODE_OPERATING_AIRLINE STRING,
    TAIL_NUMBER STRING,
    FLIGHT_NUMBER_OPERATING_AIRLINE STRING,

    ORIGIN_AIRPORT_ID NUMBER,
    ORIGIN_AIRPORT_SEQ_ID NUMBER,
    ORIGIN_CITY_MARKET_ID NUMBER,
    ORIGIN STRING,
    ORIGIN_CITY_NAME STRING,
    ORIGIN_STATE STRING,
    ORIGIN_STATE_FIPS STRING,
    ORIGIN_STATE_NAME STRING,
    ORIGIN_WAC NUMBER,

    DEST_AIRPORT_ID NUMBER,
    DEST_AIRPORT_SEQ_ID NUMBER,
    DEST_CITY_MARKET_ID NUMBER,
    DEST STRING,
    DEST_CITY_NAME STRING,
    DEST_STATE STRING,
    DEST_STATE_FIPS STRING,
    DEST_STATE_NAME STRING,
    DEST_WAC NUMBER,

    CRS_DEP_TIME STRING,
    DEP_TIME STRING,
    DEP_DELAY FLOAT,
    DEP_DELAY_MINUTES FLOAT,
    DEP_DEL15 FLOAT,
    DEPARTURE_DELAY_GROUPS STRING,
    DEP_TIME_BLK STRING,
    TAXI_OUT FLOAT,
    WHEELS_OFF STRING,
    WHEELS_ON STRING,
    TAXI_IN FLOAT,

    CRS_ARR_TIME STRING,
    ARR_TIME STRING,
    ARR_DELAY FLOAT,
    ARR_DELAY_MINUTES FLOAT,
    ARR_DEL15 FLOAT,
    ARRIVAL_DELAY_GROUPS STRING,
    ARR_TIME_BLK STRING,

    CANCELLED FLOAT,
    CANCELLATION_CODE STRING,
    DIVERTED FLOAT,

    CRS_ELAPSED_TIME FLOAT,
    ACTUAL_ELAPSED_TIME FLOAT,
    AIR_TIME FLOAT,
    FLIGHTS FLOAT,
    DISTANCE FLOAT,
    DISTANCE_GROUP NUMBER,

    CARRIER_DELAY FLOAT,
    WEATHER_DELAY FLOAT,
    NAS_DELAY FLOAT,
    SECURITY_DELAY FLOAT,
    LATE_AIRCRAFT_DELAY FLOAT,

    FIRST_DEP_TIME STRING,
    TOTAL_ADD_GTIME FLOAT,
    LONGEST_ADD_GTIME FLOAT,

    DIV_AIRPORT_LANDINGS FLOAT,
    DIV_REACHED_DEST FLOAT,
    DIV_ACTUAL_ELAPSED_TIME FLOAT,
    DIV_ARR_DELAY FLOAT,
    DIV_DISTANCE FLOAT,

    DIV1_AIRPORT STRING,
    DIV1_AIRPORT_ID STRING,
    DIV1_AIRPORT_SEQ_ID STRING,
    DIV1_WHEELS_ON STRING,
    DIV1_TOTAL_GTIME STRING,
    DIV1_LONGEST_GTIME STRING,
    DIV1_WHEELS_OFF STRING,
    DIV1_TAIL_NUM STRING,

    DIV2_AIRPORT STRING,
    DIV2_AIRPORT_ID STRING,
    DIV2_AIRPORT_SEQ_ID STRING,
    DIV2_WHEELS_ON STRING,
    DIV2_TOTAL_GTIME STRING,
    DIV2_LONGEST_GTIME STRING,
    DIV2_WHEELS_OFF STRING,
    DIV2_TAIL_NUM STRING,

    DIV3_AIRPORT STRING,
    DIV3_AIRPORT_ID STRING,
    DIV3_AIRPORT_SEQ_ID STRING,
    DIV3_WHEELS_ON STRING,
    DIV3_TOTAL_GTIME STRING,
    DIV3_LONGEST_GTIME STRING,
    DIV3_WHEELS_OFF STRING,
    DIV3_TAIL_NUM STRING,

    DIV4_AIRPORT STRING,
    DIV4_AIRPORT_ID STRING,
    DIV4_AIRPORT_SEQ_ID STRING,
    DIV4_WHEELS_ON STRING,
    DIV4_TOTAL_GTIME STRING,
    DIV4_LONGEST_GTIME STRING,
    DIV4_WHEELS_OFF STRING,
    DIV4_TAIL_NUM STRING,

    DIV5_AIRPORT STRING,
    DIV5_AIRPORT_ID STRING,
    DIV5_AIRPORT_SEQ_ID STRING,
    DIV5_WHEELS_ON STRING,
    DIV5_TOTAL_GTIME STRING,
    DIV5_LONGEST_GTIME STRING,
    DIV5_WHEELS_OFF STRING,
    DIV5_TAIL_NUM STRING,

    DUPLICATE STRING,

    EXTRA_BLANK STRING  
);



SELECT
  $1 AS airline_id,
  $2 AS name,
  $3 AS alias,
  $4 AS iata,
  $5 AS icao,
  $6 AS callsign,
  $7 AS country,
  $8 AS active
FROM @RAW.AIRLINES_STAGE
(FILE_FORMAT => RAW.FF_METADATA)
LIMIT 10;


SELECT
  $1, $2, $3, $4, $5, $6, $7, $8
FROM @RAW.AIRPORTS_STAGE
(FILE_FORMAT => RAW.FF_METADATA)
LIMIT 10;


SELECT
  $1 AS station,
  $2 AS date,
  $7 AS name,
  $10 AS visibility,
  $13 AS tmp,
  $14 AS dew
FROM @RAW.WEATHER_STAGE
(FILE_FORMAT => RAW.FF_WEATHER_BTS)
LIMIT 5;


SELECT
  $1 AS year,
  $2 AS quarter,
  $3 AS month,
  $4 AS day_of_month,
  $6 AS flight_date,
  $9 AS op_carrier_id,
  $10 AS marketing_carrier,
  $24 AS origin,
  $33 AS dest
FROM @RAW.BTS_STAGE
(FILE_FORMAT => RAW.FF_WEATHER_BTS)
LIMIT 5;


COPY INTO RAW.AIRLINES_RAW
FROM @RAW.AIRLINES_STAGE
FILE_FORMAT = (FORMAT_NAME = RAW.FF_METADATA)
ON_ERROR='CONTINUE';

COPY INTO RAW.AIRPORTS_RAW
FROM @RAW.AIRPORTS_STAGE
FILE_FORMAT = (FORMAT_NAME = RAW.FF_METADATA)
ON_ERROR='CONTINUE';


COPY INTO RAW.WEATHER_RAW
FROM @RAW.WEATHER_STAGE/jfk_2023.csv
FILE_FORMAT = (FORMAT_NAME = RAW.FF_WEATHER_BTS)
ON_ERROR='CONTINUE';



COPY INTO RAW.BTS_RAW
FROM @RAW.BTS_STAGE
FILE_FORMAT = (FORMAT_NAME = RAW.FF_WEATHER_BTS)
PATTERN='.*\\.zip'
ON_ERROR='CONTINUE';



SELECT * FROM RAW.AIRLINES_RAW LIMIT 10;
SELECT * FROM RAW.AIRPORTS_RAW LIMIT 10;
SELECT * FROM RAW.WEATHER_RAW LIMIT 10;
SELECT * FROM RAW.BTS_RAW LIMIT 10;

